
#
# Module manifest for module 'Firewall-Manager'
#
# Generated by: Markus Scholtes
#
# Generated on: 2020-02-17
#

@{

	# Script module or binary module file associated with this manifest.
	RootModule = 'Firewall-Manager.psm1'

	# Version number of this module.
	ModuleVersion = '1.0.2'

	# Supported PSEditions
	CompatiblePSEditions = 'Core, Desktop'

	# ID used to uniquely identify this module
	GUID = 'ff25bfed-b14c-2781-9c2d-cf25870696d6'

	# Author of this module
	Author = 'Markus Scholtes'

	# Company or vendor of this module
	# CompanyName = 'Unknown'

	# Copyright statement for this module
	Copyright = '(C) Markus Scholtes 2020'

	# Description of the functionality provided by this module
	Description = @'
Firewall-Manager is a module to manage firewall rules.
* Export-FirewallRules to export firewall rules to a CSV or JSON file
* Import-FirewallRules to import firewall rules from a CSV or JSON file
* Remove-FirewallRules to remove firewall rules according to a CSV or JSON file
'@

	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '4.0'

	# Name of the Windows PowerShell host required by this module
	# PowerShellHostName = ''

	# Minimum version of the Windows PowerShell host required by this module
	# PowerShellHostVersion = ''

	# Minimum version of Microsoft .NET Framework required by this module.
	# This prerequisite is valid for the PowerShell Desktop edition only.
	DotNetFrameworkVersion = '4.0'

	# Minimum version of the common language runtime (CLR) required by this module.
	# This prerequisite is valid for the PowerShell Desktop edition only.
	CLRVersion = '2.0'

	# Processor architecture (None, X86, Amd64) required by this module
	ProcessorArchitecture = 'None'

	# Modules that must be imported into the global environment prior to importing this module
	# RequiredModules = @()

	# Assemblies that must be loaded prior to importing this module
	# RequiredAssemblies = @()

	# Script files (.ps1) that are run in the caller's environment prior to importing this module.
	# ScriptsToProcess = @()

	# Type files (.ps1xml) to be loaded when importing this module
	# TypesToProcess = @()

	# Format files (.ps1xml) to be loaded when importing this module
	# FormatsToProcess = @()

	# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	# NestedModules = @()

	# Functions to export from this module, for best performance, do not use wildcards and do not
	# delete the entry, use an empty array if there are no functions to export.
	FunctionsToExport = @(
		'Export-FirewallRules',
		'Import-FirewallRules',
		'Remove-FirewallRules')

	# Cmdlets to export from this module, for best performance, do not use wildcards and do not
	# delete the entry, use an empty array if there are no cmdlets to export.
	CmdletsToExport = @()

	# Variables to export from this module
	# VariablesToExport = @()

	# Aliases to export from this module, for best performance, do not use wildcards and do not
	# delete the entry, use an empty array if there are no aliases to export.
	# AliasesToExport = @()

	# DSC resources to export from this module
	# DscResourcesToExport = @()

	# List of all modules packaged with this module
	# ModuleList = @()

	# List of all files packaged with this module
	FileList = @(
		"Firewall-Manager.psd1"
		"Firewall-Manager.psm1"
		"Export-FirewallRules.ps1"
		"Import-FirewallRules.ps1"
		"Remove-FirewallRules.ps1"
	)

	# Private data to pass to the module specified in RootModule/ModuleToProcess.
	# This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{

		PSData = @{
			# Tags applied to this module. These help with module discovery in online galleries.
			Tags = @('Firewall', 'Export', 'Import', 'FirewallRule')

			# A URL to the license for this module.
			LicenseUri = 'https://github.com/MScholtes/Firewall-Manager/blob/master/LICENSE'

			# A URL to the main website for this project.
			ProjectUri = 'https://github.com/MScholtes/Firewall-Manager'

			# A URL to an icon representing this module.
			# IconUri = ''

			# ReleaseNotes of this module
			ReleaseNotes = @'
# 1.0.2 / 2020-02-15
- First stable release
'@
		} # End of PSData hashtable
	} # End of PrivateData hashtable

	# HelpInfo URI of this module
	HelpInfoURI = 'https://github.com/MScholtes/Firewall-Manager/blob/master/README.md'

	# Default prefix for commands exported from this module.
	# Override the default prefix using Import-Module -Prefix.
	# DefaultCommandPrefix = ''
}
