
#
# Module manifest for module "Project.Windows.ProgramInfo"
#
# Generated by: metablaster
#
# Generated on: 11.2.2020.
#

@{
	# Script module or binary module file associated with this manifest.
	RootModule = "Project.Windows.ProgramInfo.psm1"

	# Version number of this module.
	ModuleVersion = "0.7.1"

	# Supported PSEditions
	CompatiblePSEditions = @(
		"Core"
		"Desktop"
	)

	# ID used to uniquely identify this module
	GUID = "49f11777-b8b6-4fed-bd82-32c8f48db81e"

	# Author of this module
	Author = "metablaster zebal@protonmail.ch"

	# Company or vendor of this module
	# CompanyName = "Unknown"

	# Copyright statement for this module
	Copyright = "Copyright (C) 2019, 2020 metablaster zebal@protonmail.ch"

	# Description of the functionality provided by this module
	Description = "Module to query software information for 'Windows Firewall Ruleset' project"

	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = "5.1"

	# Name of the Windows PowerShell host required by this module
	# PowerShellHostName = ""

	# Minimum version of the Windows PowerShell host required by this module
	# PowerShellHostVersion = ""

	# Minimum version of Microsoft .NET Framework required by this module.
	# This prerequisite is valid for the PowerShell Desktop edition only.
	DotNetFrameworkVersion = "4.8"

	# Minimum version of the common language runtime (CLR) required by this module.
	# This prerequisite is valid for the PowerShell Desktop edition only.
	CLRVersion = "4.0"

	# Processor architecture (None, X86, Amd64) required by this module
	ProcessorArchitecture = "None"

	# Modules that must be imported into the global environment prior to importing this module
	# RequiredModules = @()

	# Assemblies that must be loaded prior to importing this module
	# Required by Get-AppCapability
	RequiredAssemblies = @("Microsoft.Windows.Appx.PackageManager.Commands")

	# Script files (.ps1) that are run in the caller's environment prior to importing this module.
	# ScriptsToProcess = @()

	# Type files (.ps1xml) to be loaded when importing this module
	# TypesToProcess = @()

	# Format files (.ps1xml) to be loaded when importing this module
	# FormatsToProcess = @()

	# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	# NestedModules = @()

	# Functions to export from this module, for best performance, do not use wildcards and do not
	# delete the entry, use an empty array if there are no functions to export.
	FunctionsToExport = @(
		"Test-File"
		"Test-Installation"
		"Get-AppSID"
		"Test-Service"
		"Format-Path"
		"Test-UserProfile"
		"Find-Installation"
		"Test-Environment"
		"Get-UserSoftware"
		"Get-AllUserSoftware"
		"Get-AppCapability"
		"Get-SystemSoftware"
		"Get-ExecutablePath"
		"Get-NetFramework"
		"Get-WindowsKit"
		"Get-WindowsSDK"
		"Get-WindowsDefender"
		"Get-SQLManagementStudio"
		"Get-OneDrive"
		"Get-UserApps"
		"Get-SystemApps"
		"Get-SQLInstance"
		# Following exports only for unit testing
		"Update-Table"
		"Edit-Table"
		"Initialize-Table"
		"Show-Table"
	)

	# Cmdlets to export from this module, for best performance, do not use wildcards and do not
	# delete the entry, use an empty array if there are no cmdlets to export.
	CmdletsToExport = @()

	# Variables to export from this module
	VariablesToExport = @(
		# Following exports only for unit testing
		# "InstallTable"
	)

	# Aliases to export from this module, for best performance, do not use wildcards and do not
	# delete the entry, use an empty array if there are no aliases to export.
	AliasesToExport = @()

	# DSC resources to export from this module
	# DscResourcesToExport = @()

	# List of all modules packaged with this module
	# ModuleList = @()

	# List of all files packaged with this module
	FileList = @(
		"Project.Windows.ProgramInfo.psd1"
		"Project.Windows.ProgramInfo.psm1"
		"Project.Windows.ProgramInfo_49f11777-b8b6-4fed-bd82-32c8f48db81e_HelpInfo.xml"
		"en-US\about_Project.Windows.ProgramInfo.help.txt"
		"Help\en-US\Get-SQLInstance.md"
		"Help\en-US\Find-Installation.md"
		"Help\en-US\Format-Path.md"
		"Help\en-US\Get-AllUserSoftware.md"
		"Help\en-US\Get-AppCapability.md"
		"Help\en-US\Get-AppSID.md"
		"Help\en-US\Get-ExecutablePath.md"
		"Help\en-US\Get-NetFramework.md"
		"Help\en-US\Get-OneDrive.md"
		"Help\en-US\Get-SQLManagementStudio.md"
		"Help\en-US\Get-SystemApps.md"
		"Help\en-US\Get-SystemSoftware.md"
		"Help\en-US\Get-UserApps.md"
		"Help\en-US\Get-UserSoftware.md"
		"Help\en-US\Get-WindowsDefender.md"
		"Help\en-US\Get-WindowsKit.md"
		"Help\en-US\Get-WindowsSDK.md"
		"Help\en-US\Test-Environment.md"
		"Help\en-US\Test-File.md"
		"Help\en-US\Test-Installation.md"
		"Help\en-US\Test-Service.md"
		"Help\en-US\Test-UserProfile.md"
		"Help\README.md"
		"Private\Edit-Table.ps1"
		"Private\Initialize-Table.ps1"
		"Private\Show-Table.ps1"
		"Private\Update-Table.ps1"
		"Public\External\Get-SQLInstance.ps1"
		"Public\External\README.md"
		"Public\Find-Installation.ps1"
		"Public\Format-Path.ps1"
		"Public\Get-AllUserSoftware.ps1"
		"Public\Get-AppCapability.ps1"
		"Public\Get-AppSID.ps1"
		"Public\Get-ExecutablePath.ps1"
		"Public\Get-NetFramework.ps1"
		"Public\Get-OneDrive.ps1"
		"Public\Get-SQLManagementStudio.ps1"
		"Public\Get-SystemApps.ps1"
		"Public\Get-SystemSoftware.ps1"
		"Public\Get-UserApps.ps1"
		"Public\Get-UserSoftware.ps1"
		"Public\Get-WindowsDefender.ps1"
		"Public\Get-WindowsKit.ps1"
		"Public\Get-WindowsSDK.ps1"
		"Public\Test-Environment.ps1"
		"Public\Test-File.ps1"
		"Public\Test-Installation.ps1"
		"Public\Test-Service.ps1"
		"Public\Test-UserProfile.ps1"
	)

	# Private data to pass to the module specified in RootModule/ModuleToProcess.
	# This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{

		PSData = @{

			# Tags applied to this module. These help with module discovery in online galleries.
			Tags = @(
				"Program"
				"ProgramInfo"
				"Software"
				"SoftwareInfo"
				"ComputerSoftware"
			)

			# A URL to the license for this module.
			LicenseUri = "https://raw.githubusercontent.com/metablaster/WindowsFirewallRuleset/master/LICENSE"

			# A URL to the main website for this project.
			ProjectUri = "https://github.com/metablaster/WindowsFirewallRuleset"

			# A URL to an icon representing this module.
			# IconUri = ""

			# Prerelease string of this module
			Prerelease = "https://github.com/metablaster/WindowsFirewallRuleset/blob/master/Readme/CHANGELOG.md"

			# ReleaseNotes of this module
			# ReleaseNotes = ""

			# Flag to indicate whether the module requires explicit user acceptance for install, update, or save.
			RequireLicenseAcceptance = $false

			# A list of external modules that this module is dependent upon.
			# ExternalModuleDependencies = @()
		} # End of PSData hashtable
	} # End of PrivateData hashtable

	# HelpInfo URI of this module
	# HelpInfoURI = "https://raw.githubusercontent.com/metablaster/WindowsFirewallRuleset/master/Modules/Project.Windows.ProgramInfo/Project.Windows.ProgramInfo_49f11777-b8b6-4fed-bd82-32c8f48db81e_HelpInfo.xml"

	# Default prefix for commands exported from this module.
	# Override the default prefix using Import-Module -Prefix.
	# DefaultCommandPrefix = ""
}
