
#
# Module manifest for module 'Indented.Net.IP'
#
# Generated by: Chris Dent
#
# Generated on: 12/12/2016
#

@{
	# Script module or binary module file associated with this manifest.
	RootModule = 'Indented.Net.IP.psm1'

	# Version number of this module.
	ModuleVersion = '6.1.0'

	# Supported PSEditions
	CompatiblePSEditions = @('Core', 'Desktop')

	# ID used to uniquely identify this module
	GUID = 'da36f971-e698-46c7-bffc-5d2d35a6f505'

	# Author of this module
	Author = 'Chris Dent'

	# Company or vendor of this module
	CompanyName = 'Chris Dent'

	# Copyright statement for this module
	Copyright = 'Copyright (c) 2016 Chris Dent'

	# Description of the functionality provided by this module
	Description = 'A collection of commands written to perform IPv4 subnet math.'

	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '5.1'

	# Name of the Windows PowerShell host required by this module
	PowerShellHostName = 'ConsoleHost'

	# Minimum version of the Windows PowerShell host required by this module
	# PowerShellHostVersion = ''

	# Minimum version of Microsoft .NET Framework required by this module
	DotNetFrameworkVersion = '3.5'

	# Minimum version of the common language runtime (CLR) required by this module
	CLRVersion = '2.0'

	# Processor architecture (None, X86, Amd64) required by this module
	ProcessorArchitecture = 'None'

	# Modules that must be imported into the global environment prior to importing this module
	# RequiredModules = @()

	# Assemblies that must be loaded prior to importing this module
	# RequiredAssemblies = @()

	# Script files (.ps1) that are run in the caller's environment prior to importing this module.
	# ScriptsToProcess = @()

	# Type files (.ps1xml) to be loaded when importing this module
	# TypesToProcess = @()

	# Format files (.ps1xml) to be loaded when importing this module
	FormatsToProcess = 'Indented.Net.IP.Format.ps1xml'

	# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	# NestedModules = @()

	# Functions to export from this module
	FunctionsToExport = @(
		"ConvertFrom-HexIP"
		"ConvertTo-BinaryIP"
		"ConvertTo-DecimalIP"
		"ConvertTo-DottedDecimalIP"
		"ConvertTo-HexIP"
		"ConvertTo-Mask"
		"ConvertTo-MaskLength"
		"ConvertTo-Subnet"
		"Get-BroadcastAddress"
		"Get-NetworkAddress"
		"Get-NetworkRange"
		"Get-NetworkSummary"
		"Get-Subnet"
		"Resolve-IPAddress"
		"Test-SubnetMember"
	)

	# Cmdlets to export from this module
	# CmdletsToExport = '*'

	# Variables to export from this module
	VariablesToExport = @()

	# Aliases to export from this module
	# AliasesToExport = '*'

	# DSC resources to export from this module
	# DscResourcesToExport = @()

	# List of all modules packaged with this module
	# ModuleList = @()

	# List of all files packaged with this module
	FileList = @(
		"Indented.Net.IP.psd1"
		"Indented.Net.IP.psm1"
		"about_Indented.Net.IP.help.txt"
		"Indented.Net.IP.Format.ps1xml"
		"LICENSE"
		"README.md"
		"ConvertFrom-HexIP.ps1"
		"ConvertTo-BinaryIP.ps1"
		"ConvertTo-DecimalIP.ps1"
		"ConvertTo-DottedDecimalIP.ps1"
		"ConvertTo-HexIP.ps1"
		"ConvertTo-Mask.ps1"
		"ConvertTo-MaskLength.ps1"
		"ConvertTo-Subnet.ps1"
		"Get-BroadcastAddress.ps1"
		"Get-NetworkAddress.ps1"
		"Get-NetworkRange.ps1"
		"Get-NetworkSummary.ps1"
		"Get-Subnet.ps1"
		"Resolve-IPAddress.ps1"
		"Test-SubnetMember.ps1"
		"ConvertTo-Network.ps1"
		"Get-Permutation.ps1"
		"ConvertFrom-HexIP.md"
		"ConvertTo-BinaryIP.md"
		"ConvertTo-DecimalIP.md"
		"ConvertTo-DottedDecimalIP.md"
		"ConvertTo-HexIP.md"
		"ConvertTo-Mask.md"
		"ConvertTo-MaskLength.md"
		"ConvertTo-Subnet.md"
		"Get-BroadcastAddress.md"
		"Get-NetworkAddress.md"
		"Get-NetworkRange.md"
		"Get-NetworkSummary.md"
		"Get-Subnet.md"
		"Resolve-IPAddress.md"
		"Test-SubnetMember.md"
	)

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{

		PSData = @{

			# Tags applied to this module. These help with module discovery in online galleries.
			Tags = @('IPMaths', 'IPCalculator', 'SubnetMaths')

			# A URL to the license for this module.
			LicenseUri = 'https://github.com/metablaster/WindowsFirewallRuleset/blob/core/Modules/Indented.Net.IP/LICENSE'

			# A URL to the main website for this project.
			ProjectUri = 'https://github.com/indented-automation/Indented.Net.IP'

			# A URL to an icon representing this module.
			# IconUri = ''

			# ReleaseNotes of this module
			# ReleaseNotes = ''
		} # End of PSData hashtable
	} # End of PrivateData hashtable

	# HelpInfo URI of this module
	HelpInfoURI = 'https://github.com/metablaster/WindowsFirewallRuleset/tree/core/Modules/Indented.Net.IP/help'

	# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
	# DefaultCommandPrefix = ''
}
